/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PhysiotherapyRouteImport } from './routes/physiotherapy'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as MedicareRouteImport } from './routes/medicare'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ShopProductRefRouteImport } from './routes/shop.$productRef'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as OrdersOrderRefRouteImport } from './routes/orders.$orderRef'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysiotherapyRoute = PhysiotherapyRouteImport.update({
  id: '/physiotherapy',
  path: '/physiotherapy',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicareRoute = MedicareRouteImport.update({
  id: '/medicare',
  path: '/medicare',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsRoute,
} as any)
const ShopProductRefRoute = ShopProductRefRouteImport.update({
  id: '/$productRef',
  path: '/$productRef',
  getParentRoute: () => ShopRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramsRoute,
} as any)
const OrdersOrderRefRoute = OrdersOrderRefRouteImport.update({
  id: '/orders/$orderRef',
  path: '/orders/$orderRef',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/corporate': typeof CorporateRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/medicare': typeof MedicareRoute
  '/nutrition': typeof NutritionRoute
  '/physiotherapy': typeof PhysiotherapyRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/trainer': typeof TrainerRoute
  '/verify-email': typeof VerifyEmailRoute
  '/orders/$orderRef': typeof OrdersOrderRefRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/shop/$productRef': typeof ShopProductRefRoute
  '/programs/': typeof ProgramsIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/corporate': typeof CorporateRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/medicare': typeof MedicareRoute
  '/nutrition': typeof NutritionRoute
  '/physiotherapy': typeof PhysiotherapyRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/trainer': typeof TrainerRoute
  '/verify-email': typeof VerifyEmailRoute
  '/orders/$orderRef': typeof OrdersOrderRefRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/shop/$productRef': typeof ShopProductRefRoute
  '/programs': typeof ProgramsIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/corporate': typeof CorporateRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/medicare': typeof MedicareRoute
  '/nutrition': typeof NutritionRoute
  '/physiotherapy': typeof PhysiotherapyRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/trainer': typeof TrainerRoute
  '/verify-email': typeof VerifyEmailRoute
  '/orders/$orderRef': typeof OrdersOrderRefRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/shop/$productRef': typeof ShopProductRefRoute
  '/programs/': typeof ProgramsIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/corporate'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/medicare'
    | '/nutrition'
    | '/physiotherapy'
    | '/plans'
    | '/profile'
    | '/programs'
    | '/register'
    | '/reset-password'
    | '/shop'
    | '/signup'
    | '/trainer'
    | '/verify-email'
    | '/orders/$orderRef'
    | '/programs/$slug'
    | '/shop/$productRef'
    | '/programs/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/corporate'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/medicare'
    | '/nutrition'
    | '/physiotherapy'
    | '/plans'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/signup'
    | '/trainer'
    | '/verify-email'
    | '/orders/$orderRef'
    | '/programs/$slug'
    | '/shop/$productRef'
    | '/programs'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/corporate'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/medicare'
    | '/nutrition'
    | '/physiotherapy'
    | '/plans'
    | '/profile'
    | '/programs'
    | '/register'
    | '/reset-password'
    | '/shop'
    | '/signup'
    | '/trainer'
    | '/verify-email'
    | '/orders/$orderRef'
    | '/programs/$slug'
    | '/shop/$productRef'
    | '/programs/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CorporateRoute: typeof CorporateRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MedicareRoute: typeof MedicareRoute
  NutritionRoute: typeof NutritionRoute
  PhysiotherapyRoute: typeof PhysiotherapyRoute
  PlansRoute: typeof PlansRoute
  ProfileRoute: typeof ProfileRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRouteWithChildren
  SignupRoute: typeof SignupRoute
  TrainerRoute: typeof TrainerRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  OrdersOrderRefRoute: typeof OrdersOrderRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physiotherapy': {
      id: '/physiotherapy'
      path: '/physiotherapy'
      fullPath: '/physiotherapy'
      preLoaderRoute: typeof PhysiotherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicare': {
      id: '/medicare'
      path: '/medicare'
      fullPath: '/medicare'
      preLoaderRoute: typeof MedicareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/programs/': {
      id: '/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/shop/$productRef': {
      id: '/shop/$productRef'
      path: '/$productRef'
      fullPath: '/shop/$productRef'
      preLoaderRoute: typeof ShopProductRefRouteImport
      parentRoute: typeof ShopRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/orders/$orderRef': {
      id: '/orders/$orderRef'
      path: '/orders/$orderRef'
      fullPath: '/orders/$orderRef'
      preLoaderRoute: typeof OrdersOrderRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProgramsRouteChildren {
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

interface ShopRouteChildren {
  ShopProductRefRoute: typeof ShopProductRefRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductRefRoute: ShopProductRefRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CorporateRoute: CorporateRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MedicareRoute: MedicareRoute,
  NutritionRoute: NutritionRoute,
  PhysiotherapyRoute: PhysiotherapyRoute,
  PlansRoute: PlansRoute,
  ProfileRoute: ProfileRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRouteWithChildren,
  SignupRoute: SignupRoute,
  TrainerRoute: TrainerRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  OrdersOrderRefRoute: OrdersOrderRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
